from enum import StrEnum


class ReasonCode(StrEnum):
    AGENT_NOT_FOUND = "AGENT_NOT_FOUND"
    AGENT_REVOKED = "AGENT_REVOKED"

    POLICY_NOT_BOUND = "POLICY_NOT_BOUND"

    CAPABILITY_INVALID = "CAPABILITY_INVALID"
    CAPABILITY_EXPIRED = "CAPABILITY_EXPIRED"
    CAPABILITY_REVOKED = "CAPABILITY_REVOKED"
    CAPABILITY_SCOPE_MISMATCH = "CAPABILITY_SCOPE_MISMATCH"

    SIGNATURE_INVALID = "SIGNATURE_INVALID"

    SPEND_LIMIT_EXCEEDED = "SPEND_LIMIT_EXCEEDED"
    RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"

    WORKSPACE_MISMATCH = "WORKSPACE_MISMATCH"


def is_valid_reason_code(value: str) -> bool:
    return value in set(ReasonCode)
